omitxi= 001|7z|amgp|4ge|a2w|a5r|abap|abs|action|ada|agc|ahk|aia|aidl|aiml|akt|amw|apb|aps|arb|arq|arxml|ary|as|asc|asi|asic|asm|asmx|bak|asp|aspx|asta|asz|atomsvc|atp|ats|au3|ave|awd|axd|axs|bal|bash|bat|BDSPROJ|bmp|brm|bax|bb|bbc|bcc|bcp|bdt|beta|bgm|bml|bmo|bp|brml|brs|bsc|bsv|btproj|btq|build|bur|bxml|bzs|c|c#|CBPRO|fg|c|+|c3p|cbl|cbs|cc|cfm|cg|cmd|conf|config|cgi|cgx|ckm|classpath|clm|cls|clw|cmake|cml|cms|cob|cobol|cod|command|cos|coverage|coveragexml|cp|cpb|cpp|css|cur|dat|cpr|cpz|cs|csb|csc|cson|cspkg|csproj|csx|cuh|cx|cxx|d|datasource|dbg|dbmdl|dbml|dbp|disco|dll|doc|exe|filters|flv|gif|gif|dep|depend|derp|dev|dfb|dhtml|dic|diff|din|dist|dlg|do|dob|dpd|dpk|dpr|dproj|dqy|dsd|dso|dtd|dto|dts|dtx|dvb|dwt|e|eaf|ebc|ebx|ecore|edml|egg|info|ejs|el|eld|ema|exp|f|f90|faces|factorypath|fas|fil|flac|fmb|form|fs|fwx|gbl|gch|gcl|gcode|geojson|gfa|gnt|go|gp|gradle|graphml|greenfoot|groovy|gs|gss|gv|gyp|gypi|h|hbs|history|hkp|hlsl|hms|hs|htc|htm|html|ico|ilk|ini|html5|htr|hx|hxp|idb|idl|inc|inf|ini|ino|inp|input|ins|install|io|ipb|ipf|ipr|ips|jpg|js|irb|irobo|isa|isu|j|jad|jade|jardesc|jav|java|jbi|jcw|jdp|jl|jml|js|jsa|jsc|jsdtscope|jse|jsf|json|lnk|log|jsonp|jsp|jsx|kd|kmt|ksh|kst|kt|kts|kv|l|lap|lba|lds|less|lib|liquid|lis|lisp|lmp|loc|login|lol|lpx|lsp|lss|lst|lua|luac|map|mp3|mp4|nfo|ogg|lub|luca|lxk|m|m6m|mac|mak|master|mat|matlab|mc|mdp|mec|mel|mf|mfa|mfl|mg|mhl|mhm|mk|mkb|ml|mls|mlv|mlx|mm|mo|moc|mod|mom|mq4|mq5|mrc|mrd|mrl|mrs|mscr|mst|mvba|mw|mwp|mzp|nbk|ncb|nk|nse|nt|nupkg|nvi|o|ocb|odc|odl|opl|opv|owl|p|pdf|pag|param|pas|pbl|pbxproj|pch|pdb|pdml|perl|pf3|phl|php|png|ps2|phtml|pickle|pjt|pl|pli|plx|pm|pmp|poc|pod|ppa|ppam|prg|prl|proto|ps1|psd1|psm1|ptl|ptx|ptxml|pxml|py|pyc|rar|readme|pym|pyo|pyt|pyw|pyx|qry|qs|qvs|r|rb|rbf|rbt|rc|rc2|rcc|rdf|re|rej|resources|resx|rfs|rh|rhtml|rkt|rml|ror|rpg|rpi|rpy|rpyc|rpym|rss|rtf|sav|settings|shader|shortcuts|rts|rule|run|s|sal|sasf|sass|sax|sca|scala|scb|scpt|script|scs|scss|sct|sdl|seam|ser|sfx|sh|shfbproj|shit|sl|sln|srm|state|suo|sys|text|tiff|tmp|txt|sm|smali|spr|src|srz|ss|ssi|ssq|stm|styl|svn|base|swift|sxs|tcl|tcz|textile|tgml|thor|thtml|ti|tik|tk|tkp|tmh|toml|tpl|tpm|tra|trig|tru|ttl|twig|txml|txx|uix|ulp|uvproj|uvprojx|v4e|vb|vba|vbe|vbi|vbp|vbs|vbscript|vbw|vbx|vcp|vcproj|vcxproj|vdproj|vmx|vproj|vup|xdelta|vd|vip|viw|vjp|vls|vlx|vpc|wbf|wbt|wdl|wfs|wiki|wml|wpk|ws|wsdd|wsdl|wsf|wxl|wxs|x|xaml|xbs|xcl|xcp|xla|xlm|xme|xml|xpadderprofile|zst|xn|xpb|xsd|xsl|xslt|xui|xul|yaml|yyp|zpd|zrx|zsc|zw
omitxt:= omitxi
stringsplit,omitxtn,omitxt,= | ""
ar := Object()
Loop, %omitxtn0%
{
	new= % (omitxtn%a_index%)
	if (omitxtn%a_index% <> "")
		{
			ar.insert(new)
		}
}
stringreplace,parxti,omitxi,rar|,,All
stringreplace,parxti,parxti,7z|,,All
noBrws= Xinput_Drivers|DirectX|Visual_C++_Runtimes|Winows_Icons|IAGL|AdvancedLauncher|ICE|ROM_Collection_Browser
rjdexcl= .Mem|.Man|backdrops|.sstates|.snaps|.patches|.cheats|
rjfexcl= Folder.png|Folder.jpg|Backdrop.jpg|Backdrop.png|Banner.png|Banner.jpg|Logo.png|Logo.jpg|marquee.png|marquee.jpg|back.jpg|back.png|title.png|title.jpg|Cover.png|Cover.jpg|BoxFront.jpg|BoxFront.png|BoxBack.png|BoxBack.jpg|Spine.jpg|Spine.png|Disc.png|Disc.jpg
omtiall:= omitxt . "|" . rjdexcl
StringReplace, omitxtv, omitxt, |,`,,All
imgonl= |png|jpg|svg|bmp|jpeg|gif|
omitxj:= omitxtv
metaimages= 3DBoxart|Marquee|4Mix|3Mix|Label|Cart|Backdrop|BoxArt|Logo|Video|Metadata|Snapshot
ssenms= BoxArt|3DBoxart|Label|4Mix|cart|Logo|Marquee|Label|Logo|3DBoxart|3DBoxart|Snapshot|Logo|Label|3Mix|Backdrop|Snapshot
altnms=Folder|Back|spine|4mix|cart|logo|marquee|bezel|panel|cab_L|cab_R|tile|banner|steam|poster|fanart|snap
INJOPT=  [CUSTMOPT]| -b -e | /b -e | --windowed-fullscreen | --fullscreen | /f | -f | -FullScreen | -fs 1 | -d1 | /fullscreen /machine "COL - Colecovision" /rom1 | /fullscreen /machine "MSX" /rom1 | /fullscreen /machine "MSX2+" /rom1 | /fullscreen /machine "MSXturboR" /rom1 | /fullscreen /machine "SEGA -SG-1000" /rom1 | /fullscreen /machine "SEGA -SF-7000" /rom1 | /f /hardware:5200 /kernel:5200lle | /fullscreen /machine "SEGA -SC-3000" /rom1 | /fullscreen /machine "SVI - Spectravideo SVI-328 MK2" /rom1 | --startLoadFile | -run=dc -image=| -run=awave -rom=| -nogui -loadbin | -run=naomi -rom=| -autostart -cartcrt | -ntsc +confirmexit -saveres +warp -fullscreen -cartgeneric | -autoload | apfimag -cart | bbcm512 -cart1 | electron -flop | cpc464 -cart | gx4000 -cart | appl2cp -flop1 | apple2gs -flop1 | apple1 -cass | a2600 -cart | a5200 -cart | a7800 -cart | a800xe -flop1 | jaguar -cart | lynx -cart | xegs -cart | astrocde -cart | wswan -cart | wscolor -cart | lynx128k -flop1 | casloopy -cart | pv1000 -cart | pv2000 -cart | adam -cart1 | coleco -cart | c64 -flop | a500n -flop | a1200n -flop | a3000n -flop | cd32n -cdrm | vic20 -cart | d64plus -cart | cdtvn -cdrm | exl100 -cart | arcadia -cart | advision -cart | ep128 -cart | ep64 -cart | scv -cart | channelf -cart | fm7 -flop1 | supracan -cart | vectrex -cart | gmaster -cart | ibmpcjr -flop | vc4000 -cart | jupace -cass | samcoupe -flop1 | odyssey2 -cart | odyssey3 -cart | aquarius -cart | intv -cart | megaduck -cart | mtx512 -cass | fsa1gt -cart1 | pce -cart | tg16 -cart | sgx -cart | pce -cdrm | tg16 -cdrm | pc6001 -cart1 | pcfx | pc8801mk2 -flop1 | pc9821xs -flop1 | n64 -cart | nes -cart | famicom -cart | fds -flop | gameboy -cart | gbcolor -cart | gba -cart | vboy -cart | pokemini -cart | snes -cart | cdimono2 -cdrm | pc2000 -cart | vg5k -cass | videopac -cart | studio2 -cart | neocd -cdrm | neogeo -cart1 | aes -cart | ngp -cart | ngpc -cart | pico -cart | sc3000 -cart | sf7000 -flop | sg1000 -cart | stvbios -cart1 | 32xe -cart | 32xj -cart | 32x -cart | segacd2 -cdrm | megacd2 -cdrm | megacd2j -cdrm | dc -cdrm | dceu -cdrm | dcjp -cdrm | gamegear -cart | gamegeaj -cart | gamecom -cart1 | mz700 -cass | mz800 -cass | x1 -cart | x86kxvi -flop1 | ql_us -cass1 | psa -cdrm | pse -cdrm | psj -cdrm | psu -cdrm | pockstat -cart | m5 -flop | microtan -cart | oric -cass | mo5 -cass | 3do -cdrm | 3do_pal -cdrm | to7 -cass | crvision -cart | crvisio2 -cart | crvisioj -cart | laser200 -cass | laser310 -cass | vsmile -cart | vidbrain -cart | svisionn -cart | svisionp -cart | genesis -cart | megadriv -cart | expertdx -cart1 | canonv20s -cart1 | fmtmarty2 -cdrm | MACHINE=ARCADIA SETTINGS="WA.CFG" FULLSCREEN=ON AUTOSAVE=ON TITLEBAR=OFF TOOLBAR=OFF STRETCH=ON FILE= | -5200 -cart |  -Fullscreen 1 -MenuEnabled 0 -Region auto | --chromeless | --StartLoadFile | -32X | -sms | -scd | -gg | -md | -gen | -res=1024,768 -input-system=xinput -fullscreen | -p -f -u -c=studio -s
INJARG= [CUSTMARG]| -rp "[ROMPATH]" | -rp "[EMUPATH]\roms" | --startFullScreen | -no-printscreen-dlg | -d2 | --StartFullScreen | /A
Loop, %A_ScriptDir%\..\rj\emuCfgs\*,2
	{
		SUPEMUOPT.= A_LoopFileName . "|"
	}
mediaordert= theGamesDB|OpenVGDB|ScreenScraper|arcadeitalia|mamedb|IAGL
fesup= EmulationStation|RetroFE|Pegasus
noinstallers= |Media|Mirrored_Links|IAGL|AdvancedLauncher|ROM_Collection_Browser|MediaBrowser|ICE|
JUNCTOPT= 2
systm_cfg=DSKMNTCHK|EMGRPF|DSKMNTDDL|DSKMNTGRP|DSKSELBUT|DSKMNTOVR|EMCHKW|EMDDLF|EMDDLP|EMBUTG|EMBUTH|OPNSYS|NSys|OSys|SELAPP|SYSNICK|SvNick|DELNICK|APPOPT|APPARG|OPTTXT|ARGTXT|EMUPGC|ERUN|LRUN|NoExtn|EXTARUN|OMITQ|OMITPTH|EXDISPL
emu_lst=LOCEMUIN|MULTINST|EMUINSC|EMUINST|EMUASIGN|CHEMUINST|EMUAUTOA|RepoSet|AddRepo|GBLpgs|EMUPGC|LNCHPRDDL|LNCHPT
systm_hide=SAVNSYS|ADDNSYS|APPOPT|APPARG|NOEXTN|EMUPGC|SYSNICK|EXDISPL|SVNICK|DELNICK|ERUN|LRUN|SELAPP|OPTTXT|ARGTXT|OMITQ|EXTARUN|OMITPTH|DSKMNTGRP|DSKMNTCHK|DSKSELBUT|DSKMNTOVR|EMGRPF|EMCHKW|EMDDLP|EMDDLF|EMBUTG|EMBUTH|DSKMNTDDL
systm_show=SELAPP|APPOPT|SYSNICK|SVNICK|DELNICKmMEDIAFEITEMS=FEBUTL|FEBUTG|FEBUTH|FEBUTB|FEBUTC|FEBUTD|FEBUTE|FEBUTO|FEEDTA|FEEDTB|FELBXA|FELBXB|FEDDLE|FELNKA|FECHKG|FECHKH|FECHKI|FECHKJ|FECHKK|FEDDLC|FECHKL|FECHKM|FECHKN|FETXTG|FERAD7B|FERAD7A|FETXTI|FETXTJ|FETXTM|FEEDTD|FETXTL|FEEDTC|FEGRPA|FEPICA|FERAD4A|FERAD4B|FECHKA|FECHKB|FECHKC|FECHKD|FECHKE|FECHKG|FECHKF|FECHKO|FEDDLG|FECBXB|FERAD5A|FERAD5B|FERAD2A|FERAD2B|FERAD2C|FEBUTM|FELVA|FEDDLG|FEBUTI
FEGUIITEMS=feBUTA|feBUTB|feBUTC|feBUTG|feBUTD|feBUTE|feBUTF|feBUTH|feBUTI|feBUTJ|feBUTK|feBUTL|feBUTM|feBUTO|fePICA|fePICB|fePICC|fePICD|fePICE|fePICF|fePICG|feCHKD|feCHKE|feCHKF|feCHKG|feCHKH|feCHKI|feCHKJ|feCHKK|feCHKL|feCHKM|feCHKN|feCHKO|feCHKP|feCHKQ|feCHKA|feCHKB|feCHKC|feCBXE|feCBXF|feCBXG|feCBXH|feCBXI|feCBXJ|feCBXA|feCBXB|feCBXC|feCBXD|feDDLE|feDDLG|feDDLF|feDDLG|feDDLH|feDDLI|feLNKA|feLNKB|feDDLC|feDDLD|feDDLA|feDDLB|feEDTA|feEDTB|feEDTC|feEDTD|feEDTE|feEDTF|feEDTG|feEDTI|feUPDA|feEDTH|feUPDB|feLVA|feUPDC|feGRPA|feGRPB|feGRPC|feGRPD|feGRPE|feGRPF|feGRPG|feLBXA|feLBXB|feLVA|feLVB|feLVC|fePRGB|fePRGA|feRad5B|feRad5C|feRad4A|feRad4B|feRad5A|feRad6A|feRad6B|feRad6C|feRad6D|feRad7A|feRad7B|feRad8A|feRad8B|feRad9A|feRad9B|feRad9C|feRad10A|feRad10B|feRad11A|feRad11B|feRad2A|feRad2B|feRad2C|feRad1A|feRad3A|feRad3B|feRad3C|feRad3D|feRad1B|feSLDA|feSLDB|feSLDD|feSLDE|feSLDC|feTXTA|feTXTB|feTXTC|feTXTD|feTXTE|feTXTF|feTXTG|feTXTS|feTXTT|feTXTR|feTXTM|feTXTH|feTXTI|feTXTN|feTXTO|feTXTP|feTXTQ|feTXTJ|feTXTK|feTXTL
JACKETGUIITEMS=RJSYSRADA|RJSYSRADB|RJSYSRADC|RJSYSLOAD|RJCHKL|RJCHKH|RJCHKI|RJCHKM|RJCHKP|RJDELCOMP|RJSYSSAV|RJSYSSAVAS|RJENMAP|RJOVKM|RJMAPDD|RJMAPRET|RJMAPRETOPN|RJMAP1ROFTYPA|RJMAP1ROFTYPB|RJMAP1ROFTYPC|RJMAP1PL|RJMAP1PLOPN|RJMAP2ROFTYPA|RJMAP2ROFTYPB|RJMAP2ROFTYPC|RJMAP2PL|RJMAP2PLOPN|RJENLNCHR|RJLNCHOVR|RJRad4B|RJRad4A|RJEXEB|RJEMUPRECFG|RJEMUPRM|RJCHKQ|RJBUTM|RJCHKK|RJCHKA|RJADDSUBD|RJREMSUBD|RJSUBDCBX|RJSUBDH|RJCNSLDD|RJENCNSLD|RJENXTRARC|RJXTRARCA|RJXTRARCB|RJXTRARCDD|RJRad11A|RJRad11B|RJEDTO|RJDDLF|RJCHKW|RJBUTV|RJBUTG|RJCBXJ|RJDDLP|RJCBXH|RJBUTH|RJENDMNT|RJDMNTDD|RJDIMGET|RJRad8A|RJRad8B|RJENDMOV|RJCHKF|RJCHKO|RJPRECFGCBX|RJADDPRECFG|RJREMPRECFG|RJPOSTCFGCBX|RJADDPOSTCFG|RJREMPOSTCFG|RRJEARGSCBX|RJEMUXTCBX|RJRAD1A|RJRAD1B|RJZJP|RJCHKU|RJCHKT|RJCHKS|RJEOPTSCBX|RJCHKR|RJCHKJ
UTLGUIITEMS=utlBUTB|utlBUTC|utlBUTG|utlBUTD|utlBUTE|utlBUTF|utlBUTH|utlBUTI|utlBUTJ|utlCHKD|utlCHKE|utlCHKF|utlCHKG|utlCHKH|utlCHKI|utlCHKJ|utlCHKK|utlCHKL|utlCHKM|utlCHKN|utlCHKO|utlCHKP|utlCHKQ|utlCHKA|utlCHKB|utlCHKC|utlCBXE|utlCBXF|utlCBXG|utlCBXH|utlCBXI|utlCBXJ|utlCBXA|utlCBXB|utlCBXC|utlCBXD|utlDDLE|utlDDLF|utlDDLG|utlDDLH|utlDDLI|utlDDLJ|utlDDLC|utlDDLD|utlDDLB|utlEDTA|utlEDTB|utlEDTC|utlEDTD|utlEDTE|utlEDTF|utlEDTG|utlEDTI|utlUPDA|utlEDTH|utlUPDB|utlLVA|utlUPDC|utlGRPA|utlGRPB|utlGRPC|utlGRPD|utlGRPE|utlGRPF|utlGRPG|utlLBXA|utlLBXB|utlLVA|utlLVB|utlLVC|utlPRGB|utlPRGA|utlRad5B|utlRad5C|utlRad4A|utlRad4B|utlRad5A|utlRad6A|utlRad6B|utlRad6C|utlRad6D|utlRad7A|utlRad7B|utlRad8A|utlRad8B|utlRad9A|utlRad9B|utlRad9C|utlRad10A|utlRad10B|utlRad11A|utlRad11B|utlRad2A|utlRad2B|utlRad2C|utlRad1A|utlRad3A|utlRad3B|utlRad3C|utlRad3D|utlRad1B|utlSLDA|utlSLDB|utlSLDD|utlSLDE|utlSLDC|utlTXTA|utlPICA|utlTXTC|utlTXTD|utlTXTE|utlTXTF|utlTXTG|utlTXTS|utlTXTT|utlTXTR|utlTXTM|utlTXTH|utlTXTI|utlTXTN|utlTXTO|utlTXTP|utlTXTQ|utlTXTJ|utlTXTK|utlTXTL
ESPLRI=ESBACKUP|ESSVPL|ESPLXMP|ESCPYSCR|ESUSESCR|ESRPOPDL|ESINCLF|ESROMONLY|ESRPOPPL|ESPLCORE|ESRPOPROM|ESROMROOT|ESRRTXT|ESMIRSEL|ESDWNLPOS|ESBOXSRCHBUT|ESBOXCHK|ESMRQCHK|ESTHMBCHK|ESVIDCHK|ESMARQSRCHBUT|ESTHUMBSRCHBUT|ESVIDSRCHBUT
ESPLSWAP=ESNAMTXT|ESNAMEDT|ESPTHTXT|ESDESCTXT|ESDESCEDT|ESIMGBUT|ESIMGTXT|ESVIDPTHTXT|ESVIDTXT|ESVIDBUT|ESPTHEDT|ESSAVEOPL|ESMARQTXT|ESMARQBUT|ESMARQPTHTXT|ESOPNIMGPTHTXT|ESPUBTXT|ESPUBEDT|ESDEVTXT|ESDEVEDT|ESRATTXT|ESRATSLD|ESRLSDTXT|ESRLSDG|ESGENTXT|ESGENEDT|ESDDPLNUM|ESPLNUMTXT|ESROMPTHBUT|ESROMADDBUT|ESFLDADDBUT|ESKIDG|ESFAV|ESHIDDEN|ESTHMBTXT|ESTHUMBBUT|ESTHUMBP
ESPLITEMS=ESPLCORE|ESBACKUP|ESSVPL|ESPLXMP|ESOPENPL|ESUSESCR|ESCPYSCR|ESDWNLPOS|ESRPOPDL|ESRPOPPL|ESRPOPROM|ESMIRSEL|ESROMROOT|ESRRTXT|ESBOXSRCHBUT|ESBOXCHK|ESMRQCHK|ESTHMBCHK|ESVIDCHK|ESMARQSRCHBUT|ESTHUMBSRCHBUT|ESVIDSRCHBUT|ESNAMTXT|ESNAMEDT|ESPTHTXT|ESDESCTXT|ESDESCEDT|ESIMGBUT|ESIMGTXT|ESOPNIMGPTHTXT|ESVIDPTHTXT|ESVIDTXT|ESVIDBUT|ESPTHEDT|ESMARQTXT|ESMARQBUT|ESMARQPTHTXT|ESPUBTXT|ESPUBEDT|ESDEVTXT|ESDEVEDT|ESRATTXT|ESRATSLD|ESRLSDTXT|ESRLSDG|ESGENTXT|ESGENEDT|ESDDPLNUM|ESPLNUMTXT|ESROMPTHBUT|ESROMADDBUT|ESFLDADDBUT|ESKIDG|ESFAV|ESHIDDEN|ESTHMBTXT|ESTHUMBBUT|ESTHUMBP
SKPLISTITEMS=DWNLPOS|RECURSE|RECURTX|PLALSYSBUT|PLLISTALL|PLLISTN|PLLISTSORT|RECURTX|RPOPDL|RPOPPL|ROMPOP|PLGBA|PLGBB|PLGBC|PLGBD|CURPLST|APNDTYPGRP|PLAPPND|PLOVR|CRCEnbl|ZIPSEEK|PLCORE|DETECTCORE|SVPLST|PLNAMEDT|OPNPLST|PGCONFG|SVAPLST|CPYPL|PLADPTXT|CLRPP|PLCLRPTXT|BRADD|FENWTXT|REMPL|PLRMVTXT|MVPLOU|MVPLOD|CLRPL|PLCLRTXT|PLINIT|PLDBTXT|EXCLBOOL|INCLBOOL|PARSEALL|EXTPARSED|FLTXT|SVASPLST
PGPLRI=PGBACKUP|PGSVPL|PGPLXMP|PGCPYSCR|PGUSESCR|PGRPOPDL|PGRPOPPL|PGPLCORE|PGRPOPROM|PGROMROOT|PGRRTXT|PGMIRSEL|PGDWNLPOS|PGBOXSRCHBUT|PGBOXCHK|PGMRQCHK|PGTHMBCHK|PGVIDCHK|PGMARQSRCHBUT|PGTHUMBSRCHBUT|PGVIDSRCHBUT
PGPLSWAP=PGNAMTXT|PGNAMEDT|PGPTHTXT|PGDESCTXT|PGDESCEDT|PGIMGBUT|PGIMGTXT|PGVIDPTHTXT|PGVIDTXT|PGVIDBUT|PGPTHEDT|PGSAVEOPL|PGMARQTXT|PGMARQBUT|PGMARQPTHTXT|PGOPNIMGPTHTXT|PGPUBTXT|PGPUBEDT|PGDEVTXT|PGDEVEDT|PGRATTXT|PGRATSLD|PGRLSDTXT|PGRLSDG|PGGENTXT|PGGENEDT|PGDDPLNUM|PGPLNUMTXT|PGROMPTHBUT|PGROMADDBUT|PGFLDADDBUT|PGKIDG|PGFAV|PGHIDDEN|PGTHMBTXT|PGTHUMBBUT|PGTHUMBP
PGPLITEMS=PGPLCORE|PGBACKUP|PGSVPL|PGPLXMP|PGOPENPL|PGUSESCR|PGCPYSCR|PGDWNLPOS|PGRPOPDL|PGRPOPPL|PGRPOPROM|PGMIRSEL|PGROMROOT|PGRRTXT|PGBOXSRCHBUT|PGBOXCHK|PGMRQCHK|PGTHMBCHK|PGVIDCHK|PGMARQSRCHBUT|PGTHUMBSRCHBUT|PGVIDSRCHBUT|PGNAMTXT|PGNAMEDT|PGPTHTXT|PGDESCTXT|PGDESCEDT|PGIMGBUT|PGIMGTXT|PGOPNIMGPTHTXT|PGVIDPTHTXT|PGVIDTXT|PGVIDBUT|PGPTHEDT|PGMARQTXT|PGMARQBUT|PGMARQPTHTXT|PGPUBTXT|PGPUBEDT|PGDEVTXT|PGDEVEDT|PGRATTXT|PGRATSLD|PGRLSDTXT|PGRLSDG|PGGENTXT|PGGENEDT|PGDDPLNUM|PGPLNUMTXT|PGROMPTHBUT|PGROMADDBUT|PGFLDADDBUT|PGKIDG|PGFAV|PGHIDDEN|PGTHMBTXT|PGTHUMBBUT|PGTHUMBP
RFPLRI=RFBACKUP|RFSVPL|RFPLXMP|RFCPYSCR|RFUSESCR|RFRPOPDL|RFRPOPPL|RFPLCORE|RFRPOPROM|RFROMROOT|RFRRTXT|RFMIRSEL|RFDWNLPOS|RFBOXSRCHBUT|RFBOXCHK|RFMRQCHK|RFTHMBCHK|RFVIDCHK|RFMARQSRCHBUT|RFTHUMBSRCHBUT|RFVIDSRCHBUT
RFPLSWAP=RFNAMTXT|RFNAMEDT|RFPTHTXT|RFDESCTXT|RFDESCEDT|RFIMGBUT|RFIMGTXT|RFVIDPTHTXT|RFVIDTXT|RFVIDBUT|RFPTHEDT|RFSAVEOPL|RFMARQTXT|RFMARQBUT|RFMARQPTHTXT|RFOPNIMGPTHTXT|RFPUBTXT|RFPUBEDT|RFDEVTXT|RFDEVEDT|RFRATTXT|RFRATSLD|RFRLSDTXT|RFRLSDG|RFGENTXT|RFGENEDT|RFDDPLNUM|RFPLNUMTXT|RFROMPTHBUT|RFROMADDBUT|RFFLDADDBUT|RFKIDG|RFFAV|RFHIDDEN|RFTHMBTXT|RFTHUMBBUT|RFTHUMBP
pspce:= A_Tab . A_Space . A_Space
pspxe:= A_Tab
imgtmp= |jpg|bmp|png|jpeg|
UNUSED=OVEXTL|OVSETRM|SYSIDENT|SKPRFJTXT|OVSETTXT
RFPLITEMS=RFPLCORE|RFBACKUP|RFSVPL|RFPLXMP|RFOPENPL|RFUSESCR|RFCPYSCR|RFDWNLPOS|RFRPOPDL|RFRPOPPL|RFRPOPROM|RFMIRSEL|RFROMROOT|RFRRTXT|RFBOXSRCHBUT|RFBOXCHK|RFMRQCHK|RFTHMBCHK|RFVIDCHK|RFMARQSRCHBUT|RFTHUMBSRCHBUT|RFVIDSRCHBUT|RFNAMTXT|RFNAMEDT|RFPTHTXT|RFDESCTXT|RFDESCEDT|RFIMGBUT|RFIMGTXT|RFOPNIMGPTHTXT|RFVIDPTHTXT|RFVIDTXT|RFVIDBUT|RFPTHEDT|RFMARQTXT|RFMARQBUT|RFMARQPTHTXT|RFPUBTXT|RFPUBEDT|RFDEVTXT|RFDEVEDT|RFRATTXT|RFRATSLD|RFRLSDTXT|RFRLSDG|RFGENTXT|RFGENEDT|RFDDPLNUM|RFPLNUMTXT|RFROMPTHBUT|RFROMADDBUT|RFFLDADDBUT|RFKIDG|RFFAV|RFHIDDEN|RFTHMBTXT|RFTHUMBBUT|RFTHUMBP
UNIPLITEMS=ROMPOP|PLGBA|PLGBB|PLGBC|PLGBD|CURPLST|APNDTYPGRP|PLAPPND|PLOVR|CPYPL|PLADPTXT|CLRPP|PLCLRPTXT|BRADD|FENWTXT|REMPL|PLRMVTXT|MVPLOD|MVPLOU|CLRPL|PLCLRTXT
systmitems=SELAPP|APPOPT|SYSNICK|SVNICK|DELNICK|APPARG|NOEXTN|EMUPGC|EMUPGC|ERUN|LRUN|OMITQ|EXTARUN|OMITPTH|OPTTXT|ARGTXT|EMUINST
emu_dmnt=DSKMNTGRP|DSKMNTCHK|DSKMNTDDL|DSKSELBUT|DSKMNTOVR
emu_ppst=EMCHKW|EMDDLF|EMBUTG|EMDDLP|EMBUTH
EMUTABITEMS= SKBSRLGRP|CACGRP|GRPDROPBIOS|PRGINSTLBX|SYSINSTLBX|DWNPRGRS|EMPRLST|EMPRBUTA|EMPRDDL|EMPRBUTU|EMPRBUTX|DELCFGPGC|EMGRPF|DSKMNTGRP|DSKMNTCHK|DSKMNTDDL|DSKSELBUT|DSKMNTOVR|EMRad11B|EMCHKW|EMDDLF|EMBUTG|EMCBXH|EMDDLP|EMBUTH|RepoSet|SITEDTXT|AddRepo|EMUAUTOA|BCKCORE|UPDBTN|CCGRP|CRNTCORS|EXELIST|RALIST|SKRAstch|LNCHPRDDL|LNCHPT|ADDCORE|OPNSYS|ADDNSYS|SAVNSYS|DCORE|ARDCORE|DAPP|ASCORE|SELAPP|SYSNICK|SVNICK|DELNICK|EXTINP|APPOPT|APPARG|OPTTXT|ARGTXT|EMUPGC|ERUN|LRUN|NoExtn|OMITQ|OMITPTH|EXDISPL|UNIQLNK|INSTEMUDDL|LOCEMUIN|MULTINST|EMUINST|EMUASIGN|CHEMUINST|EINSTTXT|EINSTLOC|ROMDLOC|MROMDLOC|ROMDTXT|ROMDEDT|SKENBF|SKBEFCMD|SKRBFTXT|SKENAF|SKAFTCMD|SKRAFTXT|DISCFG|SKOVRJM|SKXPADOV|SKAMOV|SKPROFOV|SKFROV|SKFROVDD|SKRAEXE|SKRAXETXT|SKRADISP|SKIMPRATXT|SKRAIMP|SKSAVTXT|SKSAVE|SKSVAS|SKCCTXT|RAVERTXT|GRAVER|QRSETUP|EXTARUN|EMUINSC|GBLpgs
SYSINSTITEMS= SYSINSTLBX|EMPRDDL|EMPRLST|EMPRBUTA|EMPRBUTU|EMPRBUTD|EMPRBUTX|DELCFGPGC|OPNSYS|ADDCORE|OVLIST|SYSINSTLBX|EINSTTXT|EINSTLOC|CHEMUINST|INSTEMUDDL|LOCEMUIN|EMUINST|EMUASIGN|ROMDLOC|ROMDTXT|ROMDEDT
sysselitems= KARC|ADDCORE|APPARG|APPOPT|ARDCORE|CHEMUINST|DELCFGPGC|DELNICK|EMBUTG|EMBUTH|EMBUTV|EMCBXH|EMCHKW|EMDDLF|EMDDLP|EMPRBUTA|EMPRBUTU|EMPRBUTX|EMPRDDL|EMPRLST|EMUASIGN|EMUINST|EMUPGC|ERUN|EXTARUN|INSTEMUDDL|LOCEMUIN|LRUN|NOEXTN|OMITPTH|OMITQ|OPNSYS|OVLIST|ROMDLOC|SELAPP|SVNICK|SYSNICK|EMGRPF|DSKMNTGRP|OPTTXT|ARGTXT|EXDISPL|DSKMNTDDL|DSKSELBUT|DSKMNTOVR|
FEINSTITEMS= ADDREPO|CHEMUINST|DISCFG|EINSTLOC|EINSTTXT|EMUINST|INSTEMUDDL|LOCEMUIN|REPOSET|SITEDTXT|SKAFTCMD|SKAMOV|SKAMOV|SKBEFCMD|SKBSRLGRP|SKENAF|SKENBF|SKFROV|SKFROVDD|SKOVRJM|SKOVRJM|SKPROFOV|SKRAFTXT|SKRBFTXT|SKXPADOV|PRGINSTLBX
UTLINSTITEMS= REPOSET|SITEDTXT|ADDREPO|LOCEMUIN|PRGINSTLBX|EINSTTXT|EINSTLOC|CHEMUINST|EMUINST|INSTEMUDDL
EMUINSTITEMS= GRPDROPBIOS|REPOSET|SITEDTXT|ADDREPO|EMUAUTOA|PRGINSTLBX|LNCHPT|LNCHPRDDL|EINSTTXT|EINSTLOC|CHEMUINST|EMUINST|INSTEMUDDL|LOCEMUIN
PSETCFGITEMS= ADDCORE|OPNSYS|ADDNSYS|SAVNSYS|DCORE|ARDCORE|DAPP|ASCORE|SELAPP|SYSNICK|SVNICK|DELNICK|EXTINP|APPOPT|APPARG|OPTTXT|ARGTXT|EMUPGC|ERUN|LRUN|NoExtn|OMITQ|OMITPTH|EXDISPL|EXTARUN
ESFEGUIITEMS= FEBUTA|FEBUTB|FEBUTC|FEBUTD|FEBUTE|FEBUTF|FEBUTH|FEBUTG|FEBUTI|FEBUTJ|FEBUTK|FECHKB|FECHKC|FECHKD|FECHKE|FECHKF|FEEDTA|FEEDTB|FEDDLD|FEDDLA|FEDDLC|FEDDLF|FEDDLG|FECBXB|FECBXC|FECBXD|FECBXA|FELVA|FERAD5A|FERAD5B|FERAD5C|FERAD2A|FERAD2B|FESLDA|FELBXA|FEPRGA
LNCH_TUI= RUNPLRAD|RUNFLRAD|RUNROMCBX|EDTROMBTN|MORROM|SWHOST|FNDGUI|CUSTSWITCHS|CUSTMOPTS|CUSTMARGS|GROM|ESWPLCORE|LCORECBX|LCORECBX|JCORE|OPNCORE|HLNCHBUT|CLRCUROM|RETAL|RUNSYSDDL|RUNSYSCBX|RUNSYSBTN|CNCTBUT|HOSTBUTTON|LCORE|ESWPLCRE
LNCH_UI= RUNPLRAD|RUNFLRAD|RUNROMCBX|EDTROMBTN|MORROM|SWHOST|FNDGUI|CUSTSWITCHS|CUSTMOPTS|CUSTMARGS|GROM|ESWPLCORE|LCORECBX|LCORECBX|JCORE|OPNCORE|HLNCHBUT|LNCHBUT|RCLLNCH|CLRCUROM|RETAL|RUNSYSDDL|RUNSYSCBX|RUNSYSBTN|CNCTBUT|HOSTBUTTON|LCORE|ESWPLCRE
RJSYSDN= Systems
SUBDLST= .Mem||.snaps|.sstates|.Man|.patches|.cheats
SUBDLSTR:= SUBDLST
qres= 320x240|640x480|720x480|720x576|800x480|848x480|1024x600|800x600|1024x768|1152x864|1280x1024|1280x720|1280x800|1280x900|1280x960|1366x768|1360x1024|1440x900|1400x1050|1600x1024|1920x1080|1600x1024|1680x1050|1920x1200|2560x1440|3840x2160|5120x2880|7680x4320
qresf= 320x240 32bits 60hz|640x480 32bits 60hz|720x480 32bits 60hz|720x576 32bits 60hz|800x480 32bits 60hz|848x480 32bits 60hz|1024x600 32bits 60hz|800x600 32bits 60hz|1024x768 32bits 60hz|1152x864 32bits 60hz|1280x1024 32bits 60hz|1280x720 32bits 60hz|1280x800 32bits 60hz|1280x900 32bits 60hz|1280x960 32bits 60hz|1366x768 32bits 60hz|1360x1024 32bits 60hz|1440x900 32bits 60hz|1400x1050 32bits 60hz|1600x1024 32bits 60hz|1920x1080 32bits 60hz|1600x1024 32bits 60hz|1680x1050 32bits 60hz|1920x1200 32bits 60hz|2560x1440 32bits 60hz|3840x2160 32bits 60hz|5120x2880 32bits 60hz|7680x4320 32bits 60hz
CoreMI= DDLB|DDLC|DDLD|DDLE|DDLF|DDLG|DDLH|DDLI|DDLJ|DDLK|DDLL|RadA|RadB|CMBA|RadC|RadD|RadE|RadF|CHKA|CHKB|CHKC|RadG|RadH|CHKD|CHKE|CMBB|SLDA|RadI|RadJ|RadK|RadL|CHKF|CHKG|CHKH|CHKI|RadM|RadN|RadO|RadP|RadQ|RadR|RadS|RadT|RadU|RadV
SHOWARCTAB=ARCGSYS|ARCLNCH|ARCSYS|ARCMFLT|ARCLRFLT|fltrRpoBtn|ARCCORES|REDWN|DOWNONLY|CUSTSWITCH|ENHAK|MAMESWCHK|UrlTxt|ALTURLGET|ADDRPOL|SRCHEDT|SearchArc|AincTog|AexcTog|SRCHDDL|ARCPOP|CLIPURL|EXTRURL|SETOVD|JACKETMODE|OVDCHK|OVDLDS|OVDTXT|ARCDET|CLRNETP|ARCNCT|ARCHOST
HIDEARCTAB=strmvid|CUSTMOPT|CUSTMARG|EXTEXPLD|RUNXTRACT|ArcMove|ArcCull|SortOverride|ExpndASrch|SRCHRSLT|RNMJACK|ARCCBX
SORTROMTAB=SRCHDRP|KNOWNDRP|DETSORT|SELSORT|DRPSEL|MOVDRP|OVRWDRP|RENMDRP|EXTDRP|JAKDRP|KEEPSORT|ARCSORT|JAKAFT|JAKBF|DRPLV|SRTFLT|SRTCLRFLT|DATLBX|BRWSDAT|HASHALLROMS|ADDATS|ADDSRTFILE|ADDSRTDIR|DATDRPD|HLTDATP|GETDATREP|DATREPO|RDUMPDATYP|TOSECDATYP|MAMEDATYP|NOINTDATYP|DETECTXTN|DETHSHSZ
Loop,4
	{
		FAN%A_Index%ART= Backdrops
	}
Loop, 10
	{
		SNAP%A_Index%ART= Snapshots
	}
Loop,5
	{
		B%A_Index%ART= Boxart
	}
LOG1ART= Logos
LOG2ART= Logos
BANNR= Logos
BANNR1= Logos
BANNR2= Logos
VIDID= Videos
rjcaching= enabled
PLYRTYP= J
JXT= _btn
CLJXT= btn
RegionX = 0
RegionY = 0
RegionW = 820
RegionH = 620
bRegionX = 11
bRegionY = 12
bRegionW = 346
bRegionH = 485
cRegionX = 470
cRegionY = 25
cRegionW = 263
cRegionH = 94
dRegionX = 285
dRegionY = 234
dRegionW = 171
dRegionH = 123
eRegionX = 286
eRegionY = 118
eRegionW = 171
eRegionH = 73
RDXgrid= %RegionX%
RDYgrid= %RegionY%
RDWgrid= %RegionW%
RDHgrid= %RegionH%